---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ingress-monitor-controller
  name: ingress-monitor-controller
  namespace: kube-system
data:
  providers.yaml: |-
    site24x7:
      monitorDefaults:
        thresholdProfileID: "123"
