---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: ingress-monitor-controller
  name: ingress-monitor-controller
  namespace: kube-system
data:
  # These secrets just contain nonsense values, you have to override them with
  # your Site24x7 credentials.
  SITE24X7_CLIENT_ID: Y2xpZW50X2lk
  SITE24X7_CLIENT_SECRET: Y2xpZW50X3NlY3JldA==
  SITE24X7_REFRESH_TOKEN: cmVmZXNoX3Rva2Vu
